// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgtsdrenyqwqxkmemmzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndHNkcmVueXF3cXhrbWVtbXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjQwNjMsImV4cCI6MjA2NTg0MDA2M30.L_sVIKWe5wAP1rT_sTZ5pmDKaM49Wo8_yVwgDbuHiWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);